version: '3.7'

services:
    # Image project
    app:
        container_name: app_laravel
        build:
            context: .
            dockerfile: Dockerfile
        image: dockersetup/app-laravel9
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./src:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel-9
    
    # nginx
    nginx:
        container_name: nginx_laravel
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8000:80"
        volumes: 
            - ./src:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-9

    # db mysql
    mysql:
        container_name: mysql_laravel
        image: mysql:5.7.22
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: laravel_db
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            MYSQL_USER: laravel_db
        volumes: 
            - ./docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - "3306:3306"
        networks: 
            - laravel-9

    # queue
    queue:
        container_name: queue_laravel
        image: dockersetup/app-laravel9
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./src:/var/www
        depends_on: 
            - redis
            - app
        networks: 
            - laravel-9

    # redis
    redis:
        container_name: redis_laravel
        image: redis:latest
        networks: 
            - laravel-9

    #mailhog
    mailhog:
        container_name: mailhog_laravel
        image: mailhog/mailhog:latest
        logging:
            driver: 'none'
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - laravel-9

    #phpmyadmin
    phpmyadmin:
        container_name: phpmyadmin_laravel
        image: phpmyadmin:latest
        restart: unless-stopped
        depends_on:
          - mysql
        ports:
          - "8001:80"
        environment:
          - PMA_ARBITRARY=1
        networks:
          - laravel-9

    npm: 
      image: node:16.14.0
      container_name: npm_laravel
      volumes: 
        - ./src:/var/www
      working_dir: /var/www
      entrypoint: ['npm']

networks: 
    laravel-9:
        driver: bridge
